config:
  sites:
    biquge:
      name: "笔趣阁"
      url:
        chapter:
          url: '{c}'
          method: GET
          type: xpath
          encoding: gbk
        content:
          url: https://www.qu-la.com{o}
          method: GET
          type: xpath
          encoding: gbk
        search:
          url: https://so.biqusoso.com/s2.php?siteid=qu-la.com&q={k}&ie=utf-8
          method: GET
          type: xpath
          encoding: utf-8
      rules:
        chapter_name: //ul[2]/li/a/text()
        chapter_path: //ul[2]/li/a/@href
        content: //div[@class="txt"]/text()
        search_name: //span[@class="s2"]/a/text()
        search_path: //span[@class="s2"]/a/@href
      proxies:
        http: http://127.0.0.1:7890
        https: http://127.0.0.1:7890
      verify: true
      cookie:
    nanshan:
      name: "南山书院"
      url:
        chapter:
          url: https:{c}
          method: GET
          type: xpath
          encoding: gbk
        content:
          url: https://www.szyangxiao.com{o}
          method: GET
          type: xpath
          encoding: gbk
        search:
          url: https://www.szyangxiao.com/modules/article/search.php?searchkey={k}&page={p}
          method: GET
          type: xpath
          encoding: gbk
      rules:
        chapter_name: //ul/span/a/text()
        chapter_path: //ul/span/a/@href
        content: //div[@id="content"]/p/text()
        search_name: //ul/span/a[2]/text()
        search_path: //ul/span/a[1]/@href
      proxies:
      verify: true
      cookie:
    yuedsk:
      name: "阅读库"
      url:
        chapter:
          url: '{c}'
          method: GET
          type: xpath
          encoding: utf-8
        content:
          url: '{o}'
          method: GET
          type: xpath
          encoding: utf-8
        search:
          url: http://www.yuedsk.com/modules/article/search.php?q={k}
          method: GET
          type: xpath
          encoding: utf-8
      rules:
        chapter_name: //li[@class="chapter"]/a/text()
        chapter_path: //li[@class="chapter"]/a/@href
        content: //div[@id="clickeye_content"]/text()
        search_name: //div[@class="c_row"]/div[2]/div[1]/span/a/text()
        search_path: //div[@class="c_row"]/div[2]/div[1]/a/@href
      proxies:
      verify: true
      cookie:
    ibiquge:
      name: "香书小说"
      url:
        chapter:
          url: '{c}'
          method: GET
          type: xpath
          encoding: utf-8
        content:
          url: https://www.ibiquge.la/{o}
          method: GET
          type: xpath
          encoding: utf-8
        search:
          url: https://www.ibiquge.la/modules/article/waps.php
          method: POST
          data: searchkey={k}
          type: xpath
          encoding: utf-8
      rules:
        chapter_name: //dl/dd/a/text()
        chapter_path: //dl/dd/a/@href
        content: //div[@id="content"]/text()
        search_name: //td[@class="even"]/a/text()
        search_path: //td[@class="even"]/a/@href
      proxies:
        http: http://127.0.0.1:7890
        https: http://127.0.0.1:7890
      verify: true
      cookie:
    xxbiqudu:
      name: "笔趣阁2"
      url:
        chapter:
          url: https://www.xxbiqudu.com{c}
          method: GET
          type: xpath
          encoding: gbk
        content:
          url: '{o}'
          method: GET
          type: xpath
          encoding: gbk
        search:
          url: https://m.xxbiqudu.com/s.php?keyword={k}
          method: GET
          type: xpath
          encoding: gbk
      rules:
        chapter_name: //dl/dd/a/text()
        chapter_path: //dl/dd/a/@href
        content: //div[@id="content"]/text()
        search_name: //p[@class="line"]/a[2]/text()
        search_path: //p[@class="line"]/a[2]/@href
      proxies:
      verify: true
      cookie:
    fanqie:
      name: "番茄小说"
      url:
        chapter:
          url: https://www.fanqianxs.com{c}
          method: GET
          type: xpath
          encoding: utf-8
        content:
          url: https://www.fanqianxs.com{o}
          method: GET
          type: xpath
          encoding: utf-8
        search:
          url: https://www.fanqianxs.com/api/search?q={k}
          method: GET
          type: json
          encoding: utf-8
      rules:
        search_json: data.search
        chapter_name: //dl/dd/a/text()
        chapter_path: //dl/dd/a/@href
        content: //div[@id="htmlContent"]/p/text()
        search_name: book_name
        search_path: book_list_url
      proxies:
      verify: true
      cookie:
    4pan:
      name: "永恒小说"
      url:
        chapter:
          url: http://www.4pan.net{c}
          method: GET
          type: xpath
          encoding: utf-8
        content:
          url: http://www.4pan.net{d}{o}
          method: GET
          type: xpath
          encoding: utf-8
        search:
          url: http://www.4pan.net/search.php
          method: POST
          type: re
          data: key={k}
          encoding: utf-8
      rules:
        chapter_name: //li[@id="chapter"]/a/text()
        chapter_path: //li[@id="chapter"]/a/@href
        content: //div[@id="txt"]/dd/p/text()
        search_name: class="book_cov" title="([^"]+)"
        search_path: href="(/xs/\d+/\d+/)\d+.html"
      proxies:
      verify: true
      cookie:
  version: '1.1'
